import org.jetbrains.kotlin.gradle.dsl.JvmTarget

plugins {
    id 'com.android.application'
    id 'org.jetbrains.kotlin.android'
}

def keystorePropertiesFile = rootProject.file("keystore.properties")
def keystoreProperties = new Properties()
if (keystorePropertiesFile.exists()) {
    keystorePropertiesFile.withInputStream { keystoreProperties.load(it) }
}

android {
    namespace 'uk.co.cgtk.karpcalc'
    compileSdk 36

    defaultConfig {
        applicationId "uk.co.cgtk.karpcalc"
        minSdk 26
        targetSdk 36
        versionCode 14
        versionName "1.4"
    }

    lint {
        abortOnError false
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    signingConfigs {
        release {
            if (keystorePropertiesFile.exists()) {
                keyAlias keystoreProperties["keyAlias"]
                keyPassword keystoreProperties["keyPassword"]
                storeFile file(keystoreProperties["storeFile"])
                storePassword keystoreProperties["storePassword"]
            }
        }
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), '../proguard-rules.pro'
            if (keystorePropertiesFile.exists()) {
                signingConfig signingConfigs.release
            }
        }
    }

    sourceSets {
        main.manifest.srcFile '../src/androidUi/AndroidManifest.xml'
        main.res.srcDirs = ['../src/androidUi/res']
        main.java.srcDirs += '../src/main'
        main.java.srcDirs += '../src/androidUi/kotlin'
        test.java.srcDirs += '../src/test'
    }

    testOptions {
        unitTests.all {
            testLogging {
                showStandardStreams = true
                exceptionFormat = 'full'
            }
        }
    }
}

kotlin {
    compilerOptions {
        jvmTarget = JvmTarget.JVM_17
    }
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation 'androidx.appcompat:appcompat:1.7.1'
    implementation 'androidx.activity:activity-ktx:1.10.1'
    implementation 'androidx.core:core-ktx:1.16.0'
    implementation 'ch.obermuhlner:big-math:1.2.1'

    // Required for local unit tests (JUnit 4 framework)
    testImplementation 'junit:junit:4.13.2'
}

def versionInfo = tasks.register('versionInfo', Exec) {
    commandLine 'python3', '../changeset.py'
}

tasks.named('preBuild') {
    dependsOn versionInfo
}
